# This is a basic workflow that is manually triggered

name: First Workflow

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  runStarterScripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: webui
      - name: Network test
        run: |
          bash binaries.sh -s
          cd network
          bash generate.sh projectUp

        # - name: Generate coverage report
      # run:
      # |
      #   pip install pytest
      #   pip install pytest-cov
      #   pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          files: ./coverage1.xml,./coverage2.xml
          directory: ./coverage/reports/
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.gz
          verbose: true
